### ISSUE TITLE
add this to your style.css file

### ISSUE THREAD

**Issue by iamwill123** [toekki/portfolio-site-tasha-kim#2]
```css
.logo {
  background: url("../img/1-home/1-imgs/1-tk-logo.svg") no-repeat;
  width: 72px;
  height: 79px;
  transition: 500ms ease-in-out;
}

.logo:hover {
  background: url("../img/1-home/1-imgs/1-tk-logo-blk.svg") no-repeat;
  width: 72px;
  height: 79px;
  transition: 500ms ease-in-out;
}
```
